PROGRAM PrintHello(INPUT, OUTPUT);
USES 
  GPC;
BEGIN {PrintHello}
  WRITELN;
  WRITELN(GetEnv('QUERY_STRING'));
  WRITELN(GetEnv('HTTP_USER_AGENT'));
  WRITELN(GetEnv('CONTENT_LENGTH'));
  WRITELN(GetEnv('HTTP_HOST'));
  WRITELN(GetEnv('REQUEST_METHOD'));
END. {PrintHello}

